name: Build Electron App

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build and Package Electron App
        run: npm run electron:build:win

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: Setup-Maive-Caisse.exe
          path: dist-electron/*.exe
